module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/LdsQWrPsEHOGLH94fiuQ7i?mode=ac_t',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://i.ibb.co/4wB1XcHp/IMG-20250807-WA0005.jpg',
    NEWSLETTER_JID: '120363420907749813@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'ʏᴏᴠɪ ᴍɪɴɪ ʙᴏᴛ ᴠ1',
    OWNER_NAME: 'HACKER YOVI',
    OWNER_NUMBER: '9474 3281705',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> © ᴘᴏᴡᴇʀᴇᴅ ʙʏ ʏᴏᴠɪ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbBB7X96mYPMbf8not2q,
};
